name: infynitee
favicon: null
layout_spectrum: 0.08007
typography_spectrum: 0.8533915670122951
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0b10'
    - '#faf4f4'
    - '#bcafa6'
    - '#706961'
    - '#d29e00'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0
purpose: []
