name: infynitee
favicon: null
layout_spectrum: 0.08007
typography_spectrum: 0.8533915670122951
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#061d2b'
    - '#18404c'
    - '#e2ac7d'
    - '#cd8d69'
    - '#80595e'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
